config/routes.rb
GoRss::Application.routes.draw do

  devise_for :users, controllers: {sessions: "user/sessions", registrations: "user/registrations", :omniauth_callbacks => "user/omniauth_callbacks"} do
    match "/login"=> "user/sessions#new"
  end

  devise_for :admin, controllers: {sessions: "admin/sessions"} do
    match "/admin" => "admin/sessions#new"
  end

  resources :feeds, only: [:show]
  namespace :admin do
    resources :feed_urls do
      member do
        get :activate
        get :deactivate
        get :generate_feeds
        get :recolor
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do 
    resources :dashboard, only: [:index]
    resources :feed_urls do 
      member do
        get :generate_feeds
        get :subscribe
        get :unsubscribe
        get :recolor
      end
      collection do
        get :generate_all_feeds
      end
    end
    resources :categories do
      member do
        get :recolor
      end
    end
    resources :tabs, path: "bookmarks" do
      member do
        get :set_category
      end
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  before_filter :check_current_user
  # layout :false
  def index
    # @feeds = Feed.includes(:feed_url).order("created_at DESC").page(params[:page]).per(20)
    @feeds = Admin.last.subscribed_feeds.order("created_at DESC").page(params[:page]).per(20)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def check_current_user
    redirect_to user_dashboard_index_path if current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_old_index.html.erb
<!-- <div class="home-page-box">
	<%= image_tag "gorss.png" %>
</div>
<div class="home-page-box" align="center">
  <div class="signup-box">
	<%= form_for(User.new, :as => User.new , :url => registration_path(User.new), :html => { :class => 'form-horizontal' }) do |f| %>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_area', placeholder: "Enter email address here" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_area', placeholder: "Enter password here" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_area',placeholder: "Please reenter password here" %>
      </div>
    </div>
    <div class="control-group">
    	<div class="controls">
      	<%= f.submit "Sign Up", :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
  </div>
</div> -->

app/views/home/index.html.erb
<%= javascript_include_tag "coin-slider.min" %>
<%= stylesheet_link_tag "coin-slider-styles", :media => "all" %>
<%= content_for :rel_tag do %>
  <meta property="og:title" content= "<%= page_title %>" />
  <meta property="og:image" content="<%= "http://"+request.host_with_port+"/images/gorsslogo.png" %>" />
  <meta property="og:url" content="<%= "http://"+request.host_with_port %>" />
  <meta property="og:description" content="Centralize all news and updates at one place. Colurize your update types with your favourite colours." />
  <link rel="image_src" href="<%= "http://"+request.host_with_port+"/images/gorsslogo.png" %>" />
<% end %>
<style type="text/css">
  body{background: black;}
</style>
<div class="home-page">
  <div id='coin-slider'>
    <a href="javascript:void(0);">
        <img src='/images/gorss-main.jpg' >
    </a>
    <a href="javascript:void(0);">
        <img src='/images/personalize.jpg' >
    </a>
    <a href="javascript:void(0);">
        <img src='/images/view_it_large.jpg' >
    </a>
</div>
  <!-- <div class="row home-info">
    <div class="span4">
      <h1>Go-Rss</h1>
    </div>
    <div class="span8 info">
      <p>
        <strong>Do</strong> you visit different websites for news or updates every day<strong>?</strong>
      </p>
      <p>
        <strong>Do</strong> you want to centralize all news at one place<strong>?</strong> </p>
      <p>Yeh....You are at right place, choose your news sites and categories to view updates of your favourite sites. <!-- Set your favourite color for each kind of updates.</p>
      <p><%= link_to "Sign in", new_user_session_path %> to customize your dashboard. </p>
    </div> -->
  </div>
  

  <div id="feed-container" class="row">
    <div class="rss-feed-block goRssIntro">
        <div class="feed-image" >
          <%#.gsub(/\?(.*)/,"")%>
          <img src="images/gorsslogo.png" class: "f-img"/>
        </div>
      <h5><%= page_title %></h5>
      <p>
        Do you visit different websites for news or updates every day?
        <br>
        Do you want to centralize all news at one place?
        <br>
        Yeh....You are at right place, choose your news sites and categories to view updates of your favourite sites. <br>
        <%= link_to "Sign in", new_user_session_path %> to customize your dashboard. 
      </p>
      <hr>
      <div class="feed-category">
        <%= link_to new_user_session_path do %>
          <span class="label label-inverse">Signin</span>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <span class="label label-inverse">Sign Up</span>
        <% end %>
      </div>
      
    </div>
    <%= render "user/shared/feeds", feeds: @feeds %>
  </div>
</div>
<script type="text/javascript">
  var page = 1;
  $(function(){
    apply_masonry();
    //loading 
    
    var loading = false,
    finish = false;

    function nearBottomOfPage() {
      return $(window).scrollTop() > $(document).height() - $(window).height() - 50;
    }

    function finish() {
      finish = true;
    }

    $(window).scroll(function(){
      if (loading) {
        return;
      }

      if(nearBottomOfPage() && !finish) {
        loading=true;
        page++;
        $.ajax({
          url: '?page=' + page,
          type: 'get',
          dataType: 'script',
          beforeSend:  function(){
            $(".bottom-loader").show();           
          },
          success: function() {
            $(".bottom-loader").hide();
            $('#feed-container').masonry('reload');
            loading=false;
          }
        });
      }
    });


    $('#coin-slider').coinslider({width: 1366, height: 300, delay: 3000, sDelay: 50});
  })
</script>

app/views/home/index.js.erb
html = "<%= j(render 'user/shared/feeds', feeds: @feeds) %>";
$("#feed-container").append( html );
image_loading_callback();