config/routes.rb
GoRss::Application.routes.draw do

  devise_for :users, controllers: {sessions: "user/sessions", registrations: "user/registrations", :omniauth_callbacks => "user/omniauth_callbacks"} do
    match "/login"=> "user/sessions#new"
  end

  devise_for :admin, controllers: {sessions: "admin/sessions"} do
    match "/admin" => "admin/sessions#new"
  end

  resources :feeds, only: [:show]
  namespace :admin do
    resources :feed_urls do
      member do
        get :activate
        get :deactivate
        get :generate_feeds
        get :recolor
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do 
    resources :dashboard, only: [:index]
    resources :feed_urls do 
      member do
        get :generate_feeds
        get :subscribe
        get :unsubscribe
        get :recolor
      end
      collection do
        get :generate_all_feeds
      end
    end
    resources :categories do
      member do
        get :recolor
      end
    end
    resources :tabs, path: "bookmarks" do
      member do
        get :set_category
      end
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/feed_url.rb
class FeedUrl < ActiveRecord::Base

	STATUSES = {active: "ACTIVE", pending: "PENDING"}

  attr_accessible :description, :title, :url
  validates :url, uniqueness: true, presence: true, format: /http?:\/\/[\S]+/
  validate :title, presence: true
  # validates :status, inclusion: {in: STATUSES.map{|i,v| v}}

  before_validation :parse_rss
  # validate :parsable?

  has_many :feeds
  has_many :user_feed_url, dependent: :destroy
  has_many :users, through: :user_feed_url

  STATUSES.each do |method_name, value|
		define_method method_name.to_s+"?" do
			status == value
		end
  end


  def activate
  	self.status= STATUSES[:active]
  	save!
  end

  def deactivate
  	self.status= STATUSES[:pending]
  	save!
  end

  def generate_feed
  	feed = RssParser::RssFeed.parse_rss_url(url)
    if feed
    	feed.entries.each do |e|
        old_f = feeds.where("guid=?",(e.entry_id || e.link)).first
    		new_f = feeds.build(data: e) unless old_f
        new_f.save if new_f
    	end
    	# save
    end
  end

  def subscribed_by?(user)
    users.find_by_id(user.id)
  end

  def self.generate_all_feeds
    objs = []
    urls = FeedUrl.all#where("status=?",STATUSES[:active])
    Feed.order("created_at ASC").limit(2000).destroy_all if Feed.count>7000
    urls.each do |u|
      feed = RssParser::RssFeed.parse_rss_url(u.url)
      feed.entries.each do |e|
        old_f = Feed.where("guid=?",(e.entry_id || e.link)).first
        new_f = u.feeds.build(data: e) unless old_f
        objs << new_f if new_f
      end if feed
    end
    objs.shuffle!
    objs.each do |f|
      f.save
    end
  end

  private

  def parse_rss
    return if title
  	feed = RssParser::RssFeed.parse_rss_url(url) rescue nil
  	unless feed
  		errors[:url] << "not able to parse."
  	else
  		self.title = feed.title
  		self.description = feed.description
  		self.status = STATUSES[:active]
  	end
  end

end

app/models/user.rb
class User < Person
	devise :registerable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :user_feed_url
  has_many :feed_urls, through: :user_feed_url
  has_many :categories
  has_many :tabs
  after_create :subscribe_all_feeds

  def subscribe(feed_url)
    sub =user_feed_url.build(feed_url_id: feed_url.id)
    sub.save
  end

  def unsubscribe(feed_url)
    user_feed_url.find_by_feed_url_id(feed_url.id).try(:destroy)
  end

  def generate_feeds
    objs = []
    urls = feed_urls.where("status=?",STATUSES[:active])
    urls.each do |u|
      feed = RssParser::RssFeed.parse_rss_url(u.url)
      feed.entries.each do |e|
        old_f = Feed.where("guid=?",(e.entry_id || e.link)).first
        new_f = u.feeds.build(data: e) unless old_f
        objs << new_f if new_f
      end
    end
    objs.shuffle!
    objs.each do |f|
      f.save
    end
  end

  # 1 -- 10
  # 2 -- 11 20
  def subscribed_feeds
    # page = page ? page.to_i : 1
    # limit = 10
    # off = (page-1) * limit + 1

    urls = feed_urls.where("status=?",FeedUrl::STATUSES[:active]).select("feed_urls.id")
     # urls = feed_urls.where("status=?",FeedUrl::STATUSES[:active]).pluck("feed_urls.id").join(",")
    # Feed.find_by_sql("Select distinct f.id, f.*, u.color,u.id as u_id from user_feed_urls u LEFT JOIN feeds f ON f.feed_url_id=u.feed_url_id where u.user_id = #{self.id} and u.feed_url_id in (#{urls}) ORDER BY f.created_at DESC LIMIT #{limit}  OFFSET #{off}")
    Feed.joins("LEFT JOIN user_feed_urls ON feeds.feed_url_id=user_feed_urls.feed_url_id LEFT JOIN feed_urls fu ON fu.id=feeds.feed_url_id").select("distinct feeds.*, user_feed_urls.color, fu.title as url_title").where("feeds.feed_url_id in (?) and user_feed_urls.user_id=?", urls.map(&:id),self.id)
  end

  def subscribed_feed_urls
    # user_feed_urls.joins(:feed_urls).select("")
    # feed_urls.joins(:user_feed_url).select("feed_urls.*, user_feed_urls.color")#.uniq("feed_urls.id")
    feed_urls.joins(:user_feed_url).select(" distinct feed_urls.id, feed_urls.*, user_feed_urls.color")#.uniq("feed_urls.id")
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def subscribe_all_feeds
    FeedUrl.all.each{|u|subscribe(u)}
  end
end

app/controllers/admin/feed_urls_controller.rb
class Admin::FeedUrlsController < Admin::BaseController
  # GET /feed_urls
  # GET /feed_urls.json
  def index
    @feed_urls = current_user.feed_urls

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_urls }
    end
  end

  # GET /feed_urls/1
  # GET /feed_urls/1.json
  def show
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/new
  # GET /feed_urls/new.json
  def new
    @feed_url = FeedUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/1/edit
  def edit
    @feed_url = FeedUrl.find(params[:id])
  end

  # POST /feed_urls
  # POST /feed_urls.json
  def create
    @feed_url = FeedUrl.new(params[:feed_url])

    respond_to do |format|
      if @feed_url.save
        format.html { redirect_to [:admin,@feed_url], notice: 'Feed url was successfully created.' }
        format.json { render json: @feed_url, status: :created, location: @feed_url }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feed_urls/1
  # PUT /feed_urls/1.json
  def update
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      if @feed_url.update_attributes(params[:feed_url])
        format.html { redirect_to [:admin,@feed_url], notice: 'Feed url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_urls/1
  # DELETE /feed_urls/1.json
  def destroy
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.destroy

    respond_to do |format|
      format.html { redirect_to admin_feed_urls_url }
      format.json { head :no_content }
    end
  end

  def activate
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.activate
    redirect_to admin_feed_urls_path

  end


  def deactivate
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.deactivate
    redirect_to admin_feed_urls_path

  end

  def generate_feeds
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.generate_feed
    redirect_to admin_feed_urls_path
  end

  def recolor
    @feed_url = FeedUrl.find(params[:id])
    @user_feed_url = (current_user.user_feed_url.where(feed_url_id: @feed_url.id).last || current_user.user_feed_url.create(feed_url_id: @feed_url.id) )
    @user_feed_url.recolor("#"+params[:color])
    render nothing: true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	def index
		@users = User.all
	end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/user/categories_controller.rb
class User::CategoriesController < User::BaseController
  before_filter :find_catergory, except: [:create]
  def create
    @category = current_user.categories.build(params[:category])
    @category.save
  end

  def recolor
  	@category.recolor(params[:color])
  end

  def destroy
  	@category.destroy
  end

  private
  def find_catergory
  	@category = current_user.categories.find(params[:id])
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::BaseController
  def index
  	@feeds = current_user.subscribed_feeds.order("created_at DESC").page(params[:page]).per(20)
    @feed_urls = current_user.subscribed_feed_urls
  	respond_to do |format|
  		format.html
  		format.js
    end
  end
end

app/controllers/user/feed_urls_controller.rb
class User::FeedUrlsController < User::BaseController
  before_filter :find_feed_url, only: [:generate_feeds, :subscribe, :unsubscribe, :recolor]
  def index
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
  end

  def new
    @feed_url = FeedUrl.new
  end

  def create
    @feed_url = FeedUrl.new(params[:feed_url])
    @feed_url.save
  end

	def generate_feeds
    @feed_url.generate_feed
    redirect_to user_dashboard_index_path
  end

  def subscribe
    current_user.subscribe(@feed_url)
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
    respond_to do |format|
     format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  def unsubscribe
    current_user.unsubscribe(@feed_url)
    respond_to do |format|
      format.html{redirect_to user_dashboard_index_path}
      format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
      end
    end
  end

  def recolor
    @user_feed_url = current_user.user_feed_url.where(feed_url_id: @feed_url.id).last
    @user_feed_url.recolor("#"+params[:color])
  end

  def generate_all_feeds
  	FeedUrl.generate_all_feeds
    respond_to do |format|
  	 format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  private
  def find_feed_url
    @feed_url = FeedUrl.find(params[:id])
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	
	private

	def after_sign_up_path_for(resource)
		user_dashboard_index_path
	end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
	
	private

	def after_sign_in_path_for(resource)
		user_dashboard_index_path
	end
end

app/controllers/user/tabs_controller.rb
class User::TabsController < User::BaseController
  def index
    @category = Category.new
    @tab = Tab.new
    @categories = current_user.categories.all.blank? ? [current_user.categories.create(name: "Default")] :  current_user.categories
  end

  def create
    @tab = current_user.tabs.build(params[:tab])
    @tab.save
  end

  def destroy
    @tab = current_user.tabs.find(params[:id])
    @tab.destroy
  end

  def new
    @tab = Tab.new
    @categories = current_user.categories.all.blank? ? [current_user.categories.create(name: "Default")] :  current_user.categories
  end

  def set_category
    @tab = current_user.tabs.find(params[:id])
    @tab.update_attribute(:category_id, params[:category_id]) if current_user.categories.find(params[:category_id])
    respond_to  do |format|
      format.js{render layout: false}
    end
  end


end

app/helpers/feed_urls_helper.rb
module FeedUrlsHelper
end

app/helpers/user/dashboard_helper.rb
module User::DashboardHelper
end

app/helpers/user/feed_urls_helper.rb
module User::FeedUrlsHelper
end

app/views/user/feed_urls/_feed_urls.html.erb
<div>
  <ul class="win8-menu">
    <% feed_urls.each do |feed_url| %>
      <li class="all-feed-url">
        <%= feed_url.title %> 
        <% unless feed_url.pending? %>
            <% if feed_url.subscribed_by?(current_user) %>
              <%= link_to content_tag(:i, "", class:"icon-refresh"), generate_feeds_user_feed_url_path(feed_url) %>
              <%= link_to content_tag(:i, "", class:"icon-remove danger"), unsubscribe_user_feed_url_path(feed_url), class: "danger"%>
            <% else %>
              <%= link_to content_tag(:i, "", class:"icon-magnet danger"), subscribe_user_feed_url_path(feed_url),title:"Subscribe",  remote: true %>
            <% end %>
          <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/user/feed_urls/_form.html.erb
<div id="new_feed_url_div" class="center-popup" style= "height: 100px !important;">
  <button type="button" class="close" data-dismiss="center-popup">&times;</button>
  <%= form_for [:user, @feed_url], html:{class: 'form-inline'}, remote: true do |f| %>
    <div class="span4 error-container">

    </div>
    <div class="content span4">
      <div class="input-append row">
        <%= f.text_field :url, class: "span3" %>
        <button class="btn" type="submit">Go!</button>
        <%#= f.submit "Go!", class: "btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/user/feed_urls/_side_menu_feed_url.html.erb
<li class="subscribed-feed feed-url-<%= feed_url.id %>">
  <div class="color_box" data-feed-url-id="<%= feed_url.id %>" data-url="<%=recolor_user_feed_url_path(feed_url) %>" ></div>
  <%= link_to content_tag(:i, "", class:"icon-refresh"), generate_feeds_user_feed_url_path(feed_url) %> 
  <%= feed_url.title %> 
  <%= link_to content_tag(:i, "", class:"icon-remove danger"), unsubscribe_user_feed_url_path(feed_url), class: "danger", remote: true%> 
</li>

app/views/user/feed_urls/create.js.erb
<% if @feed_url.errors.any? %>
  $("#new_feed_url_div form .error-container").html("<span class='errors'><%= @feed_url.errors.full_messages.join(", ").html_safe %></span>")
<% else %>
  $(".overlay").fadeOut();
  $("#new_feed_url_div").fadeOut(function(){$(this).remove()});
<% end %>

app/views/user/feed_urls/generate_all_feeds.js.erb
html = "<%= j(render 'user/shared/feeds', feeds: @feeds) %>";
$("#feed-container").html(html).masonry('reload');
image_loading_callback();
page = 1;

app/views/user/feed_urls/index.html.erb
<%= render "feed_urls", feed_urls: @feed_urls %>

app/views/user/feed_urls/index.js.erb
html = "<%= j(render 'feed_urls', feed_urls: @feed_urls) %>"
$(".popup .content").append(html);
show_popup();
$("html, body").animate({scrollTop: "0px"})

app/views/user/feed_urls/new.js.erb
$("body").animate({"scroll-top": "0px"}, function(){
  html = "<%= j(render 'form') %>"
  $("#new_feed_url_div").remove();
  overlay()
  $(".navbar").append(html)
  $("#new_feed_url_div").center();
})

app/views/user/feed_urls/recolor.js.erb
$(".feed_url_<%= @feed_url.id %>").css({"background-color": "<%= @user_feed_url.color.bg %>"})
$(".feed_url_<%= @feed_url.id %> h5 a").css({"color": "<%= @user_feed_url.color.heading %>"})

app/views/user/feed_urls/subscribe.js.erb
html = "<%= j(render 'user/shared/feeds', feeds: @feeds) %>";
$("#feed-container").html(html).masonry('reload');
image_loading_callback();
page = 1;

html = "<%= j(render 'side_menu_feed_url', feed_url: @feed_url) %>";
$(".side-menu .subscribed-rss").append(html);
add_item($(".side-menu .feed-url-<%= @feed_url.id %>"));
html = "<%= j(render 'feed_urls', feed_urls: @feed_urls) %>"
$(".popup .content").html(html);
show_popup();
$(".bottom-loader").hide();
apply_color_picker()

app/views/user/feed_urls/unsubscribe.js.erb
html = "<%= j(render 'user/shared/feeds', feeds: @feeds) %>";
$("#feed-container").html(html).masonry('reload');
image_loading_callback();
page = 1;


remove_item($(".side-menu .feed-url-<%= @feed_url.id %>"));