config/routes.rb
GoRss::Application.routes.draw do

  devise_for :users, controllers: {sessions: "user/sessions", registrations: "user/registrations", :omniauth_callbacks => "user/omniauth_callbacks"} do
    match "/login"=> "user/sessions#new"
  end

  devise_for :admin, controllers: {sessions: "admin/sessions"} do
    match "/admin" => "admin/sessions#new"
  end

  resources :feeds, only: [:show]
  namespace :admin do
    resources :feed_urls do
      member do
        get :activate
        get :deactivate
        get :generate_feeds
        get :recolor
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do 
    resources :dashboard, only: [:index]
    resources :feed_urls do 
      member do
        get :generate_feeds
        get :subscribe
        get :unsubscribe
        get :recolor
      end
      collection do
        get :generate_all_feeds
      end
    end
    resources :categories do
      member do
        get :recolor
      end
    end
    resources :tabs, path: "bookmarks" do
      member do
        get :set_category
      end
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :color
  serialize :color#, FeedColor
  validates :name, presence: true,length:{maximum: 50}, uniqueness: {scope: :user_id}
  belongs_to :user
  has_many :tabs
  
  def recolor(clr)
    cl = FeedColor.new(clr)
    update_attribute(:color, cl )
  end
end

app/models/user.rb
class User < Person
	devise :registerable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :user_feed_url
  has_many :feed_urls, through: :user_feed_url
  has_many :categories
  has_many :tabs
  after_create :subscribe_all_feeds

  def subscribe(feed_url)
    sub =user_feed_url.build(feed_url_id: feed_url.id)
    sub.save
  end

  def unsubscribe(feed_url)
    user_feed_url.find_by_feed_url_id(feed_url.id).try(:destroy)
  end

  def generate_feeds
    objs = []
    urls = feed_urls.where("status=?",STATUSES[:active])
    urls.each do |u|
      feed = RssParser::RssFeed.parse_rss_url(u.url)
      feed.entries.each do |e|
        old_f = Feed.where("guid=?",(e.entry_id || e.link)).first
        new_f = u.feeds.build(data: e) unless old_f
        objs << new_f if new_f
      end
    end
    objs.shuffle!
    objs.each do |f|
      f.save
    end
  end

  # 1 -- 10
  # 2 -- 11 20
  def subscribed_feeds
    # page = page ? page.to_i : 1
    # limit = 10
    # off = (page-1) * limit + 1

    urls = feed_urls.where("status=?",FeedUrl::STATUSES[:active]).select("feed_urls.id")
     # urls = feed_urls.where("status=?",FeedUrl::STATUSES[:active]).pluck("feed_urls.id").join(",")
    # Feed.find_by_sql("Select distinct f.id, f.*, u.color,u.id as u_id from user_feed_urls u LEFT JOIN feeds f ON f.feed_url_id=u.feed_url_id where u.user_id = #{self.id} and u.feed_url_id in (#{urls}) ORDER BY f.created_at DESC LIMIT #{limit}  OFFSET #{off}")
    Feed.joins("LEFT JOIN user_feed_urls ON feeds.feed_url_id=user_feed_urls.feed_url_id LEFT JOIN feed_urls fu ON fu.id=feeds.feed_url_id").select("distinct feeds.*, user_feed_urls.color, fu.title as url_title").where("feeds.feed_url_id in (?) and user_feed_urls.user_id=?", urls.map(&:id),self.id)
  end

  def subscribed_feed_urls
    # user_feed_urls.joins(:feed_urls).select("")
    # feed_urls.joins(:user_feed_url).select("feed_urls.*, user_feed_urls.color")#.uniq("feed_urls.id")
    feed_urls.joins(:user_feed_url).select(" distinct feed_urls.id, feed_urls.*, user_feed_urls.color")#.uniq("feed_urls.id")
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def subscribe_all_feeds
    FeedUrl.all.each{|u|subscribe(u)}
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	def index
		@users = User.all
	end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/user/categories_controller.rb
class User::CategoriesController < User::BaseController
  before_filter :find_catergory, except: [:create]
  def create
    @category = current_user.categories.build(params[:category])
    @category.save
  end

  def recolor
  	@category.recolor(params[:color])
  end

  def destroy
  	@category.destroy
  end

  private
  def find_catergory
  	@category = current_user.categories.find(params[:id])
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::BaseController
  def index
  	@feeds = current_user.subscribed_feeds.order("created_at DESC").page(params[:page]).per(20)
    @feed_urls = current_user.subscribed_feed_urls
  	respond_to do |format|
  		format.html
  		format.js
    end
  end
end

app/controllers/user/feed_urls_controller.rb
class User::FeedUrlsController < User::BaseController
  before_filter :find_feed_url, only: [:generate_feeds, :subscribe, :unsubscribe, :recolor]
  def index
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
  end

  def new
    @feed_url = FeedUrl.new
  end

  def create
    @feed_url = FeedUrl.new(params[:feed_url])
    @feed_url.save
  end

	def generate_feeds
    @feed_url.generate_feed
    redirect_to user_dashboard_index_path
  end

  def subscribe
    current_user.subscribe(@feed_url)
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
    respond_to do |format|
     format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  def unsubscribe
    current_user.unsubscribe(@feed_url)
    respond_to do |format|
      format.html{redirect_to user_dashboard_index_path}
      format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
      end
    end
  end

  def recolor
    @user_feed_url = current_user.user_feed_url.where(feed_url_id: @feed_url.id).last
    @user_feed_url.recolor("#"+params[:color])
  end

  def generate_all_feeds
  	FeedUrl.generate_all_feeds
    respond_to do |format|
  	 format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  private
  def find_feed_url
    @feed_url = FeedUrl.find(params[:id])
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	
	private

	def after_sign_up_path_for(resource)
		user_dashboard_index_path
	end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
	
	private

	def after_sign_in_path_for(resource)
		user_dashboard_index_path
	end
end

app/controllers/user/tabs_controller.rb
class User::TabsController < User::BaseController
  def index
    @category = Category.new
    @tab = Tab.new
    @categories = current_user.categories.all.blank? ? [current_user.categories.create(name: "Default")] :  current_user.categories
  end

  def create
    @tab = current_user.tabs.build(params[:tab])
    @tab.save
  end

  def destroy
    @tab = current_user.tabs.find(params[:id])
    @tab.destroy
  end

  def new
    @tab = Tab.new
    @categories = current_user.categories.all.blank? ? [current_user.categories.create(name: "Default")] :  current_user.categories
  end

  def set_category
    @tab = current_user.tabs.find(params[:id])
    @tab.update_attribute(:category_id, params[:category_id]) if current_user.categories.find(params[:category_id])
    respond_to  do |format|
      format.js{render layout: false}
    end
  end


end

app/helpers/user/dashboard_helper.rb
module User::DashboardHelper
end

app/helpers/user/feed_urls_helper.rb
module User::FeedUrlsHelper
end

app/views/user/categories/_category.html.erb
<div class="rss-feed-block tab-cat-block" id="category_<%= category.id %>" style="background: <%= category_bg(category) %>">
  <div class="color_box" data-feed-url-id="<%= category.id %>" data-url="<%=recolor_user_category_path(category) %>" data-bg="<%= category_bg(category) %>" style="background: <%= category_bg(category) %>"  ></div>
  <%= link_to [:user,category], method: "delete", remote: true, class: "remove_cat", title: "Remove category",style: "color: #{category_dark(category)}" do %>
    <i class="icon-remove-circle"></i>
  <%end%>
  <h5 style="color: <%=category_dark(category)%>"><%= category.name %></h5>
  <ul id="category_ul_<%= category.id %>" class="tabs_ul" "data-catid"="<%= category.id %>">
    <% category.tabs.each do |t| %>
      <%= render t, category: category %>
    <% end %>
    
  </ul>
  <ul>
    <li style="background: <%= category_dark(category) %>">
      <span>Add New Tab</span>
      <a href="javascript:void(0)" class="new_link" style="color: <%=category_bg(category)%>">
        <i class="icon-share-alt"></i>
      </a>
      <%= form_for [:user, Tab.new], remote: true, html: {class: "tab_form new_form", style: "display: none"} do |tf| %>
        <%= tf.text_field :name , placeholder: "Enter name"%>
        <%= tf.text_field :url, placeholder: "Enter url" %>
        <%= tf.hidden_field :category_id, value: category.id %>
        <button class="btn" type="button">Add Tab</button>
      <%end%>
    </li>
  </ul>
  <hr>
</div>

app/views/user/categories/create.js.erb
<% if @category.errors.any? %>
  alert("<%= @category.errors.full_messages.join(',')%>")
<% else %>
  $(".new_category_form input").val("")
  html = "<%= j(render @category).html_safe %>";
  $(".categories_container").append(html);
  $('#feed-container').masonry('reload');
  apply_dragable_tabs()
  apply_color_picker()
<% end %>

app/views/user/categories/destroy.js.erb
$("#category_<%= @category.id %>").remove()
$(".bottom-loader").hide();
$('#feed-container').masonry('reload');

app/views/user/categories/recolor.js.erb
$("#category_<%= @category.id%>").replaceWith("<%= j(render @category) %>")
$('#feed-container').masonry('reload');
apply_color_picker()