config/routes.rb
GoRss::Application.routes.draw do

  devise_for :users, controllers: {sessions: "user/sessions", registrations: "user/registrations", :omniauth_callbacks => "user/omniauth_callbacks"} do
    match "/login"=> "user/sessions#new"
  end

  devise_for :admin, controllers: {sessions: "admin/sessions"} do
    match "/admin" => "admin/sessions#new"
  end

  resources :feeds, only: [:show]
  namespace :admin do
    resources :feed_urls do
      member do
        get :activate
        get :deactivate
        get :generate_feeds
        get :recolor
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do 
    resources :dashboard, only: [:index]
    resources :feed_urls do 
      member do
        get :generate_feeds
        get :subscribe
        get :unsubscribe
        get :recolor
      end
      collection do
        get :generate_all_feeds
      end
    end
    resources :categories do
      member do
        get :recolor
      end
    end
    resources :tabs, path: "bookmarks" do
      member do
        get :set_category
      end
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/feed_url.rb
class FeedUrl < ActiveRecord::Base

	STATUSES = {active: "ACTIVE", pending: "PENDING"}

  attr_accessible :description, :title, :url
  validates :url, uniqueness: true, presence: true, format: /http?:\/\/[\S]+/
  validate :title, presence: true
  # validates :status, inclusion: {in: STATUSES.map{|i,v| v}}

  before_validation :parse_rss
  # validate :parsable?

  has_many :feeds
  has_many :user_feed_url, dependent: :destroy
  has_many :users, through: :user_feed_url

  STATUSES.each do |method_name, value|
		define_method method_name.to_s+"?" do
			status == value
		end
  end


  def activate
  	self.status= STATUSES[:active]
  	save!
  end

  def deactivate
  	self.status= STATUSES[:pending]
  	save!
  end

  def generate_feed
  	feed = RssParser::RssFeed.parse_rss_url(url)
    if feed
    	feed.entries.each do |e|
        old_f = feeds.where("guid=?",(e.entry_id || e.link)).first
    		new_f = feeds.build(data: e) unless old_f
        new_f.save if new_f
    	end
    	# save
    end
  end

  def subscribed_by?(user)
    users.find_by_id(user.id)
  end

  def self.generate_all_feeds
    objs = []
    urls = FeedUrl.all#where("status=?",STATUSES[:active])
    Feed.order("created_at ASC").limit(2000).destroy_all if Feed.count>7000
    urls.each do |u|
      feed = RssParser::RssFeed.parse_rss_url(u.url)
      feed.entries.each do |e|
        old_f = Feed.where("guid=?",(e.entry_id || e.link)).first
        new_f = u.feeds.build(data: e) unless old_f
        objs << new_f if new_f
      end if feed
    end
    objs.shuffle!
    objs.each do |f|
      f.save
    end
  end

  private

  def parse_rss
    return if title
  	feed = RssParser::RssFeed.parse_rss_url(url) rescue nil
  	unless feed
  		errors[:url] << "not able to parse."
  	else
  		self.title = feed.title
  		self.description = feed.description
  		self.status = STATUSES[:active]
  	end
  end

end

app/controllers/admin/feed_urls_controller.rb
class Admin::FeedUrlsController < Admin::BaseController
  # GET /feed_urls
  # GET /feed_urls.json
  def index
    @feed_urls = current_user.feed_urls

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_urls }
    end
  end

  # GET /feed_urls/1
  # GET /feed_urls/1.json
  def show
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/new
  # GET /feed_urls/new.json
  def new
    @feed_url = FeedUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed_url }
    end
  end

  # GET /feed_urls/1/edit
  def edit
    @feed_url = FeedUrl.find(params[:id])
  end

  # POST /feed_urls
  # POST /feed_urls.json
  def create
    @feed_url = FeedUrl.new(params[:feed_url])

    respond_to do |format|
      if @feed_url.save
        format.html { redirect_to [:admin,@feed_url], notice: 'Feed url was successfully created.' }
        format.json { render json: @feed_url, status: :created, location: @feed_url }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feed_urls/1
  # PUT /feed_urls/1.json
  def update
    @feed_url = FeedUrl.find(params[:id])

    respond_to do |format|
      if @feed_url.update_attributes(params[:feed_url])
        format.html { redirect_to [:admin,@feed_url], notice: 'Feed url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_urls/1
  # DELETE /feed_urls/1.json
  def destroy
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.destroy

    respond_to do |format|
      format.html { redirect_to admin_feed_urls_url }
      format.json { head :no_content }
    end
  end

  def activate
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.activate
    redirect_to admin_feed_urls_path

  end


  def deactivate
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.deactivate
    redirect_to admin_feed_urls_path

  end

  def generate_feeds
    @feed_url = FeedUrl.find(params[:id])
    @feed_url.generate_feed
    redirect_to admin_feed_urls_path
  end

  def recolor
    @feed_url = FeedUrl.find(params[:id])
    @user_feed_url = (current_user.user_feed_url.where(feed_url_id: @feed_url.id).last || current_user.user_feed_url.create(feed_url_id: @feed_url.id) )
    @user_feed_url.recolor("#"+params[:color])
    render nothing: true
  end
end

app/controllers/user/feed_urls_controller.rb
class User::FeedUrlsController < User::BaseController
  before_filter :find_feed_url, only: [:generate_feeds, :subscribe, :unsubscribe, :recolor]
  def index
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
  end

  def new
    @feed_url = FeedUrl.new
  end

  def create
    @feed_url = FeedUrl.new(params[:feed_url])
    @feed_url.save
  end

	def generate_feeds
    @feed_url.generate_feed
    redirect_to user_dashboard_index_path
  end

  def subscribe
    current_user.subscribe(@feed_url)
    @feed_urls = FeedUrl.all #.page(params[:page]).per(10)
    respond_to do |format|
     format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  def unsubscribe
    current_user.unsubscribe(@feed_url)
    respond_to do |format|
      format.html{redirect_to user_dashboard_index_path}
      format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
      end
    end
  end

  def recolor
    @user_feed_url = current_user.user_feed_url.where(feed_url_id: @feed_url.id).last
    @user_feed_url.recolor("#"+params[:color])
  end

  def generate_all_feeds
  	FeedUrl.generate_all_feeds
    respond_to do |format|
  	 format.html{redirect_to user_dashboard_index_path}
     format.js do 
        @feeds = current_user.subscribed_feeds.order("created_at DESC").limit(20)
     end
    end
  end

  private
  def find_feed_url
    @feed_url = FeedUrl.find(params[:id])
  end
end

app/helpers/feed_urls_helper.rb
module FeedUrlsHelper
end

app/helpers/user/feed_urls_helper.rb
module User::FeedUrlsHelper
end

app/views/admin/feed_urls/_form.html.erb
<%= form_for [:admin,@feed_url], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :url, :class => 'text_area' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_feed_urls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/feed_urls/edit.html.erb
<%- model_class = FeedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/feed_urls/index.html.erb
<%- model_class = FeedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @feed_urls.each do |feed_url| %>
      <tr>
        <td><%= link_to feed_url.id, admin_feed_url_path(feed_url) %></td>
        <td><%= feed_url.title %></td>
        <td><%= feed_url.status %></td>
        <td><%=l feed_url.created_at %></td>
        <td>
          <div class="color_box" data-feed-url-id="<%= feed_url.id %>" data-url="<%=recolor_admin_feed_url_path(feed_url) %>" data-bg="<%= feed_bg_color(feed_url) %>" style="background: <%= feed_bg_color(feed_url) %>"  ></div>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_feed_url_path(feed_url), :class => 'btn btn-mini' %>
          <% if feed_url.pending? %>
            <%= link_to t('.activate', :default => t("helpers.links.activate")),
                      activate_admin_feed_url_path(feed_url), :class => 'btn btn-mini' %>
          <% else %>
            <%= link_to t('.deactivate', :default => t("helpers.links.deactivate")),
                      deactivate_admin_feed_url_path(feed_url), :class => 'btn btn-mini' %>
            <%= link_to "Generate Feed", generate_feeds_admin_feed_url_path(feed_url), :class => 'btn btn-mini' %>
          <% end %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_feed_url_path(feed_url),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_feed_url_path,
            :class => 'btn btn-primary' %>

app/views/admin/feed_urls/new.html.erb
<%- model_class = FeedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/feed_urls/show.html.erb
<%- model_class = FeedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @feed_url.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @feed_url.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @feed_url.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_feed_urls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_feed_url_path(@feed_url), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_feed_url_path(@feed_url),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>